spring:
  application:
    name: ProjectCT_TLCN

  # Data JPA settings
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL}
  jackson:
    time-zone: ${TIME_ZONE}

  # Message
  messages:
    basename: messages
    encoding: UTF-8

  # Mail service
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

#Server
server:
  address: ${SERVER_ADDRESS}
  port: ${SERVER_PORT}

#Constant
time_zone: ${TIME_ZONE}